#!/bin/sh
f=$d/$artifactId/pom.xml
### ADD *derby* dependencies ###
saxonb-xslt -s:$f -xsl:$xslDir/pom/addDependency.xsl -o:$f groupId=org.apache.derby artifactId=derby version=10.9.1.0
saxonb-xslt -s:$f -xsl:$xslDir/pom/addDependency.xsl -o:$f groupId=org.apache.derby artifactId=derbytools version=10.9.1.0

dp=$d/$artifactId/src/main/resources/META-INF/persistence.xml
### UPDATE jdbc properties to *derby* in persistence.xml ###
saxonb-xslt -s:$dp -xsl:$xslDir/persistence/updateProperty.xsl -o:$dp persistenceUnitName=$persistenceUnitName propertyName=javax.persistence.jdbc.driver propertyValue='org.apache.derby.jdbc.EmbeddedDriver'
saxonb-xslt -s:$dp -xsl:$xslDir/persistence/updateProperty.xsl -o:$dp persistenceUnitName=$persistenceUnitName propertyName=javax.persistence.jdbc.url propertyValue='jdbc:derby:testD;create=true' # jdbc:derby:memory:testD
saxonb-xslt -s:$dp -xsl:$xslDir/persistence/updateProperty.xsl -o:$dp persistenceUnitName=$persistenceUnitName propertyName=javax.persistence.jdbc.user propertyValue='je'
saxonb-xslt -s:$dp -xsl:$xslDir/persistence/updateProperty.xsl -o:$dp persistenceUnitName=$persistenceUnitName propertyName=javax.persistence.jdbc.password propertyValue='je'

