#!/bin/sh
### ADD datanucleus dependencies ###
saxonb-xslt -s:$f -xsl:$xslDir/pom/addDependency.xsl -o:$f groupId=javax.jdo artifactId=jdo-api version=3.0
saxonb-xslt -s:$f -xsl:$xslDir/pom/addDependency.xsl -o:$f groupId=org.apache.geronimo.specs artifactId=geronimo-jpa_2.0_spec version=1.1
saxonb-xslt -s:$f -xsl:$xslDir/pom/addDependency.xsl -o:$f groupId=org.datanucleus artifactId=datanucleus-core version='[3.2.0-m2, 3.2.99)'
saxonb-xslt -s:$f -xsl:$xslDir/pom/addDependency.xsl -o:$f groupId=org.datanucleus artifactId=datanucleus-api-jpa version='[3.2.0-m2, 3.2.99)'
saxonb-xslt -s:$f -xsl:$xslDir/pom/addDependency.xsl -o:$f groupId=log4j artifactId=log4j version='[1.2, 1.3)'

### ADD the pom properties ###
saxonb-xslt -s:$f -xsl:$xslDir/pom/addProperty.xsl -o:$f propertyName=this.persistenceUnitName propertyValue=persistenceUnit
saxonb-xslt -s:$f -xsl:$xslDir/pom/addProperty.xsl -o:$f propertyName=project.build.sourceEncoding propertyValue=UTF-8

### ADD the pluginRepositories element as a child of <project> element ###
saxonb-xslt -s:$f -xsl:$xslDir/pom/addChildToProject.xsl -o:$f elementName=pluginRepositories

### ADD the datanucleus repository ###
echo '<tempXXX>
  <snapshots>
    <enabled>false</enabled>
  </snapshots>
</tempXXX>' > $d/$artifactId/support/dataNucleus-repositoryExtra.xml
saxonb-xslt -s:$f -xsl:$xslDir/pom/addRepository.xsl -o:$f id=DN_M2_Repo name='DataNucleus Repository' url=http://www.datanucleus.org/downloads/maven2 extraXML=$d/$artifactId/support/dataNucleus-repositoryExtra.xml
sed -i '/tempXXX/d' $f

# Now add the datanucleus plugin repository
saxonb-xslt -s:$f -xsl:$xslDir/pom/addPluginRepository.xsl -o:$f id=DataNucleus_2 url=http://www.datanucleus.org/downloads/maven2/ extraXML=$d/$artifactId/support/dataNucleus-repositoryExtra.xml
sed -i '/tempXXX/d' $f

# Add the extra plugins
# 1) the datanucleus-maven-plugin...
echo '<tempXXX>
  <configuration>
    <api>JPA</api>
    <persistenceUnitName>${this.persistenceUnitName}</persistenceUnitName>
    <log4jConfiguration>${basedir}/log4j.properties</log4jConfiguration>
    <verbose>false</verbose>
  </configuration>
  <executions>
    <execution>
      <phase>compile</phase>
      <goals>
        <goal>enhance</goal>
      </goals>
      </execution>
  </executions>
</tempXXX>' > $d/$artifactId/support/datanucleus-maven-pluginExtra.xml
saxonb-xslt -s:$f -xsl:$xslDir/pom/addPlugin.xsl -o:$f groupId=org.datanucleus artifactId=datanucleus-maven-plugin version=3.2.0-m3 extraXML=$d/$artifactId/support/datanucleus-maven-pluginExtra.xml
sed -i '/tempXXX/d' $f

# 2) the exec-maven-plugin...
echo '<tempXXX>
  <configuration>
    <mainClass>${this.mainClass}</mainClass>
    <systemProperties>
      <systemProperty>
        <key>log4j.configuration</key>
        <value>file:${basedir}/log4j.properties</value>
      </systemProperty>
    </systemProperties>
  </configuration>
</tempXXX>' > $d/$artifactId/support/exec-maven-pluginExtra.xml
saxonb-xslt -s:$f -xsl:$xslDir/pom/addPlugin.xsl -o:$f groupId=org.codehaus.mojo artifactId=exec-maven-plugin version=1.1 extraXML=$d/$artifactId/support/exec-maven-pluginExtra.xml
sed -i '/tempXXX/d' $f

# 3) the maven-assembly-plugin
echo '<tempXXX>
  <configuration>
    <descriptors>
      <descriptor>${basedir}/assembly.xml</descriptor>
    </descriptors>
  </configuration>
</tempXXX>' > $d/$artifactId/support/maven-assembly-pluginExtra.xml
saxonb-xslt -s:$f -xsl:$xslDir/pom/addPlugin.xsl -o:$f groupId=org.apache.maven.plugins artifactId=maven-assembly-plugin version=2.4 extraXML=$d/$artifactId/support/maven-assembly-pluginExtra.xml
sed -i '/tempXXX/d' $f

### Now update persistence.xml ###
dp=$d/$artifactId/src/main/resources/META-INF/persistence.xml
# Update the JPA persistence provider
saxonb-xslt -s:$dp -xsl:$xslDir/persistence/deleteElement.xsl -o:$dp persistenceUnitName=$persistenceUnitName elementName=provider
saxonb-xslt -s:$dp -xsl:$xslDir/persistence/addElement.xsl -o:$dp persistenceUnitName=$persistenceUnitName elementName=provider elementValue=org.datanucleus.jpa.PersistenceProviderImpl

# Add property to create the schema automatically
saxonb-xslt -s:$dp -xsl:$xslDir/persistence/addProperty.xsl -o:$dp persistenceUnitName=$persistenceUnitName propertyName=datanucleus.autoCreateSchema propertyValue=true

